load:
  extract_columns: [
      'headline',
      'category',
    ]
dataset:
  filter_columns: [
      'headline',
      'category',
    ]
  label_column: 'category'

training:
  train_test_split:
    test_size: 0.33
    random_state: 42